[package]
name = "bif"
readme = "README.md"
description = "Roku BIF encoder/decoder"
authors = ["Brendon Walsh <brendonwalsh@niamu.com>"]
repository = "https://github.com/niamu/bif"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
structopt = "0.3.26"
